config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :saved_filters do
    get 'activate', on: :collection
    get 'deactivate', on: :collection
  end

  devise_for :users

  root to: 'home#index'

  # resource :weather, only: :index,
  #
  get 'weather_forecasts/get_weather_forecast',
      to: 'weather_forecasts#get_weather_forecast',
      as: :get_weather_forecast

  get 'flights/:id/anywhere',
      to: 'cities#anywhere',
      as: :flights_to_anywhere

  get 'flights/:city_from/:city_to',
      to: 'cities#flights_to_selected_city',
      as: :flights_to_selected_city

  resources :cities, only: %i[index show] do
    get :flights_statistics, on: :member
  end

  # Admin part
  get '/admin', to: 'admin#index', as: :admin_home

  scope :admin, module: :admin, as: :admin do
    root to: 'home#index'

    resources :cities do
      resources :opportunities
      resources :hotel_reservations
      resources :flights

      get 'destinations', on: :member, as: :cheapest
      get 'stats', on: :member, as: :stats
    end

    resources :countries
  end

  # Utilities
  require 'sidekiq/web'
  require "fastentry/engine"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Fastentry::Engine, at: '/fastentry'
  end

  mount ActionCable.server => '/cable'

  authenticate :user, ->(user) { user.has_role? :admin } do
    mount PgHero::Engine, at: 'pghero'
  end
end

app/models/flight.rb
# frozen_string_literal: true

class Flight < ApplicationRecord
  # after_create :get_weather
  after_create :find_relevant_subscriptions

  enum source: { cheapest: 1, latest: 2, nearest: 3, direct: 4 }
  enum state: { active: 0, archived: 0 }
  enum currency: { USD: 0, RUB: 1, EUR: 2, UAH: 3, BYN: 4 }

  belongs_to :opportunity, optional: :true

  # validates :date_from, :date_to, :cost, :city_to_id, presence: true

  belongs_to :city_from, class_name: 'City', optional: true, foreign_key: :city_from_id
  belongs_to :city_to, class_name: 'City', optional: true, foreign_key: :city_to_id

  scope :order_scope, ->(col, direction = :asc) { eval("order(#{col}: :#{direction})") if col.present? }

  scope :by_arriving_city, lambda { |_city|
    return self unless _city.present?

    joins('INNER JOIN cities AS arriving_cities ON arriving_cities.id = flights.city_to_id')
      .where("arriving_cities.code = '#{_city}'")
  }

  scope :by_source, lambda { |source|
    return self unless source.present?

    where(source: source)
  }

  scope :by_max_price, lambda { |price|
    return self unless price.present?

    where('cost <= ?', price)
  }

  scope :by_departing_date, lambda { |dates|
    return self unless dates.present?

    date = Date.strptime(dates, '%d.%m.%Y')
    where('DATE(date_from) >= ?', date)
  }

  scope :by_arriving_date, lambda { |dates|
    return self unless dates.present?

    date = Date.strptime(dates, '%d.%m.%Y')
    where('DATE(date_to) <= ?', date)
  }

  scope :by_including_dates, lambda { |dates|
    return self unless dates.present?

    dates = dates.split(',')
    return self if dates.count != 2

    date_from = Date.strptime(dates[0], '%d.%m.%Y')
    date_to = Date.strptime(dates[1], '%d.%m.%Y')

    where('DATE(date_from) <= ? AND DATE(date_to) >= ?', date_from, date_to)
  }

  scope :expired, lambda {
    Flight
      .where('DATE(date_from) < ?', Date.today)
      .where('opportunity_id IS ?', nil)
      .where(smallest_price: false)
      .or(Flight.where('DATE(expires_at) > ?', Date.today))
      .or(Flight.where("created_at < DATE('#{3.months.ago.strftime('%Y-%m-%d')}')"))
  }

  scope :broken, lambda {
    where('city_to_id is ?', nil)
      .where(smallest_price: false)
      .where(cost: nil)
      .or(Flight.where('city_from_id is ?', nil))

    # .or(Flight.where("created_at < DATE('#{ 3.months.ago.strftime('%Y-%m-%d') }')"))
  }

  scope :statistics, lambda { |city_id|
    where(created_at: 30.days.ago..Date.current)
      .where(city_from_id: city_id)
      .where(smallest_price: false)
      .group('date(flights.created_at)')
      .count
  }

  def duration
    return 0 unless date_to.present? && date_from.present?

    (date_to - date_from).to_i
  end

  def link
    content = 'https://hydra.aviasales.ru/searches/new?marker=182694'
    content += "&origin_iata=#{city_from.code}"
    content += "&destination_iata=#{city_to.code}"
    content += "&depart_date=#{date_from}"
    content += "&return_date=#{date_to}&with_request=true"

    content
  end

  def booking_link
    booking_id = city_to.booking_api

    return nil if booking_id.nil?

    "https://www.booking.com/searchresults.ru.html?city=#{booking_id}
      &nflt=review_score%253D90%253Breview_score%253D80
      &aid=1627894
      &checkin_monthday=#{date_from.day}
      &checkin_month=#{date_from.month}
      &checkin_year=#{date_from.year}
      &checkout_monthday=#{date_to.day}
      &checkout_month=#{date_from.month}
      &checkout_year=#{date_from.year}
      &no_rooms=1
      &group_adults=1"
  end

  def weather_forecasts
    WeatherForecast.where(city_id: city_to_id, day: date_from..date_to)
  end

  def get_weather
    WeatherForFlightWorker.perform_async
  end

  def find_relevant_subscriptions
    flight_params = {
      city_to: city_to_id,
      city_from: city_from_id,
      date_from: date_from,
      date_to: date_to,
      price: cost,
      duration: duration,
      city_to_title: city_to&.title,
      id: id
    }

    RelevantFlightsSearcherWorker.perform_async(flight_params)
    # RelevantFlightsSearcherWorker.new.perform(flight_params)
  end

  def email_row
    # <td class='table__cell'>#{ self.city_to.title }</td>

    "
      <tr class='table__row'>
        <td class='table__cell'>#{I18n.localize(date_from, format: '%d %b')}</td>
        <td class='table__cell'>#{I18n.localize(date_to, format: '%d %b')}</td>
        <td class='table__cell'>#{cost}</td>
        <td class='table__cell'><a href='#{link}'>Aviasales</a></td>
      </tr>
    "
  end
end

app/controllers/admin/flights_controller.rb
# frozen_string_literal: true

class Admin::FlightsController < AdminController
  before_action :set_flight, only: %i[show edit update destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.includes(:city_from, :city_to).all.to_json(include: %i[city_from city_to])
  end

  # GET /flights/1
  # GET /flights/1.json
  def show; end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit; end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flight
    @flight = Flight.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flight_params
    params.require(:flight).permit(:title, :slug, :date_from, :date_to, :country_id)
  end
end

app/controllers/flights_controller.rb
# frozen_string_literal: true

class FlightsController < ApplicationController
  before_action :set_flight, only: %i[show edit update destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  def show; end

  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit; end

  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_flight
    @flight = Flight.find(params[:id])
  end

  def flight_params
    params.require(:flight).permit(:title, :slug, :date_from, :date_to, :country_id, :date_in)
  end
end

app/views/flights/_desktop_flight_row.html.slim
tr.tr [
  data-source='#{ flight.source }'
  itemscope
  itemtype='http://schema.org/Product' ]
  / td = flight.id
  td = city_name_by_locale(flight.city_to)
  td = flight.cost
  td = l(flight.date_from, format: '%d %b %Y')
  td = l(flight.date_to, format: '%d %b %Y')
  td = flight.duration
  / td = l(flight.created_at, format: '%d %b %H:%M')
  td = flight.number_of_changes
  / th
  /   = render 'shared/weather_short', forecasts: flight.weather_forecasts, cached: true
  /   = button_tag 'Прогноз погоды',
  /     class: 'button  is-link is-small',
  /     data: { selector: 'getWeatherButton', city_id: @city.id, date_from: flight.date_from, date_to: flight.date_to }
  td
    = link_to 'Aviasales',
      flight.link,
      target: :blank,
      class: 'button  is-link is-small',
      data: { selector: 'openAviasales' },
      rel: 'nofollow'
  td
    - booking_link = flight.booking_link
    - if booking_link
      = link_to 'Booking',
        flight.booking_link,
        target: :blank,
        class: 'button  is-link is-small',
        data: { selector: 'openAviasales' },
        rel: 'nofollow'
  td
    = button_tag 'Погода',
      class: 'button  is-link is-small',
      data: { action: 'flights-list#getWeather',
        city: flight.city_to_id,
        date_from: flight.date_from,
        date_to: flight.date_to }
      / | Из #{ flight.city_from.title } в #{ flight.city_to.title } по #{ flight.cost } вылет #{ flight.date_from } возврат #{ flight.date_to }

app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :date_from %>
    <%= form.date_select :date_from %>
  </div>

  <div class="field">
    <%= form.label :date_to %>
    <%= form.date_select :date_to %>
  </div>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.text_field :country_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flights/_list.html.slim
div data-controller='flights-list'
  .is-hidden-desktop
    = render partial: 'flights/mobile_flight_row',
      collection: @flights,
      cached: true,
      as: :flight

  .is-hidden-touch
    table.table.is-hoverable.is-fullwidth
      thead.thead
        tr
          / th #
          th width='200px' = link_to 'В', sort_flights_link(:city_to_id), data: { turbolinks: false }
          th = link_to 'Цена', sort_flights_link(:cost), data: { turbolinks: false }
          th = link_to 'Вылет', sort_flights_link(:date_from), data: { turbolinks: false }
          th = link_to ' Возвращение', sort_flights_link(:date_to), data: { turbolinks: false }
          / th = link_to ' Длительность', sort_flights_link(:duration)
          th Длительность
          / th = link_to ' Опубликован',sort_flights_link(:created_at), data: { turbolinks: false }
          th Пересадки
          / th Погода
          th Билеты
          th Гостиница
          th Погода
      tbody.tbody data-target='latest-flights-filter.flightsList'
        = render partial: 'flights/desktop_flight_row',
          collection: @flights,
          cached: true,
          as: :flight

  div data-turbolinks='false'
    = will_paginate @flights

app/views/flights/_mobile_flight_row.html.slim
.card
  .card-header
    .card-header-title = flight.city_to.title
  .card-content
    div Стоимость: #{ flight.cost }
    div Туда-обратно: #{ l(flight.date_from, format: '%d %b %Y') } - #{ l(flight.date_to, format: '%d %b %Y') }
    div Длительность: #{ flight.duration }
    / div Дата обновления: #{ l(flight.created_at, format: '%d %b %H:%M') }
    / div Количество пересадок: #{ flight.number_of_changes }
  / div Погода
  / div = render 'shared/weather_short', forecasts: flight.weather_forecasts, cached: true
  .card-footer
    = link_to 'Билеты на Aviasales',
      flight.link,
      target: :blank,
      class: 'card-footer-item',
      rel: 'nofollow'

    - booking_link = flight.booking_link
    - if booking_link
      = link_to 'Гостиницы на Booking',
        flight.booking_link,
        target: :blank,
        class: 'card-footer-item',
        data: { selector: 'openAviasales' },
        rel: 'nofollow'

    = button_tag 'Погода',
      class: 'card-footer-item buttonAsLink',
      data: { action: 'flights-list#getWeather',
        city: flight.city_to_id,
        date_from: flight.date_from,
        date_to: flight.date_to }
br

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Date from</th>
      <th>Date to</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.title %></td>
        <td><%= flight.slug %></td>
        <td><%= flight.date_from %></td>
        <td><%= flight.date_to %></td>
        <td><%= flight.country %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @flight.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @flight.slug %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @flight.date_from %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @flight.date_to %>
</p>

<p>
  <strong>Country:</strong>
  <%= @flight.country %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>