config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :saved_filters do
    get 'activate', on: :collection
    get 'deactivate', on: :collection
  end

  devise_for :users

  root to: 'home#index'

  # resource :weather, only: :index,
  #
  get 'weather_forecasts/get_weather_forecast',
      to: 'weather_forecasts#get_weather_forecast',
      as: :get_weather_forecast

  get 'flights/:id/anywhere',
      to: 'cities#anywhere',
      as: :flights_to_anywhere

  get 'flights/:city_from/:city_to',
      to: 'cities#flights_to_selected_city',
      as: :flights_to_selected_city

  resources :cities, only: %i[index show] do
    get :flights_statistics, on: :member
  end

  # Admin part
  get '/admin', to: 'admin#index', as: :admin_home

  scope :admin, module: :admin, as: :admin do
    root to: 'home#index'

    resources :cities do
      resources :opportunities
      resources :hotel_reservations
      resources :flights

      get 'destinations', on: :member, as: :cheapest
      get 'stats', on: :member, as: :stats
    end

    resources :countries
  end

  # Utilities
  require 'sidekiq/web'
  require "fastentry/engine"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Fastentry::Engine, at: '/fastentry'
  end

  mount ActionCable.server => '/cable'

  authenticate :user, ->(user) { user.has_role? :admin } do
    mount PgHero::Engine, at: 'pghero'
  end
end

app/models/opportunity.rb
# frozen_string_literal: true

class Opportunity < ApplicationRecord
  has_one :flight, dependent: :destroy
  has_one :hotel_reservation, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  accepts_nested_attributes_for :flight, :hotel_reservation, allow_destroy: true

  def duration
    (flight.date_to - flight.date_from).to_i
  end
end

app/controllers/admin/opportunities_controller.rb
# frozen_string_literal: true

module Admin
  class OpportunitiesController < AdminController
    before_action :set_opportunity, only: %i[show edit update destroy]
    before_action :set_city, only: %i[index show edit update destroy]

    # GET /opportunities
    # GET /opportunities.json
    def index
      @opportunities = Opportunity.all
    end

    # GET /opportunities/1
    # GET /opportunities/1.json
    def show; end

    # GET /opportunities/new
    def new
      @opportunity = Opportunity.new
      @opportunity.build_hotel_reservation
      @opportunity.build_flight
    end

    # GET /opportunities/1/edit
    def edit; end

    # POST /opportunities
    # POST /opportunities.json
    def create
      @opportunity = Opportunity.new(description: opportunity_params[:description])
      @opportunity.flight = Flight.find(opportunity_params['flight_attributes']['id'])
      @opportunity.image = nil

      respond_to do |format|
        if @opportunity.save
          format.html { redirect_to admin_city_opportunities_path, notice: 'Opportunity was successfully created.' }
        # format.json { render :show, status: :created, location: @opportunity }
        else
          format.html { render :new }
          # format.json { render json: @opportunity.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /opportunities/1
    # PATCH/PUT /opportunities/1.json
    def update
      respond_to do |format|
        if @opportunity.update(opportunity_params)
          format.html { redirect_to @opportunity, notice: 'Opportunity was successfully updated.' }
          format.json { render :show, status: :ok, location: @opportunity }
        else
          format.html { render :edit }
          format.json { render json: @opportunity.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /opportunities/1
    # DELETE /opportunities/1.json
    def destroy
      @opportunity.destroy
      respond_to do |format|
        format.html { redirect_to opportunities_url, notice: 'Opportunity was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_opportunity
      @opportunity = Opportunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def opportunity_params
      params
        .require(:opportunity)
        .permit(:flight_id,
                :hotel_reservation_id,
                :image,
                :description,
                hotel_reservation_attributes: %i[id title],
                flight_attributes: %i[id title])
    end

    def set_city
      @city = City.find(params[:city_id])
    end
  end
end

app/controllers/opportunities_controller.rb
# frozen_string_literal: true

class OpportunitiesController < ApplicationController
  before_action :set_opportunity, only: %i[show edit update destroy]

  # GET /opportunities
  # GET /opportunities.json
  def index
    @opportunities = Opportunity.includes(:flight, :hotel_reservation).all
  end

  # GET /opportunities/1
  # GET /opportunities/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_opportunity
    @opportunity = Opportunity.find(params[:id])
  end
end

app/views/admin/opportunities/_form.html.slim
. data-controller="new-opportunity"

  h1 data-target="new-opportunity.output"

  = simple_form_for([:admin, :city, opportunity], local: true) do |form|
    - if opportunity.errors.any?
      #error_explanation
        h2
          = "#{ pluralize(opportunity.errors.count, "error") } prohibited this opportunity from being saved:"
        
        ul
          - opportunity.errors.full_messages.each do |message|
            li
              = message
    / .field
    /   = form.label :image
    /   = form.file_field :image
    /
    / br

    .field
      = form.label :description
      = form.input :description, label: false

    = form.fields_for :hotel_reservation do |hotel_form|
      / h1 Отель
      / .field
      /   | Страна отеля
      /   = hotel_form.label :title
      /   = hotel_form.text_field :title
      / .field
      /   | название отеля
      /   = hotel_form.label :title
      /   = hotel_form.text_field :title
      / .field
      /   | Дата с - по
      /   = hotel_form.label :title
      /   = hotel_form.text_field :title
      / .field
      /   | Цена
      /   = hotel_form.label :title
      /   = hotel_form.text_field :title
      / .field
      /   | Ссылка на предложение
      /   = hotel_form.label :title
      /   = hotel_form.text_field :title

    = form.fields_for :flight do |flight_form|
      h1 Самолёт

      .field
        = flight_form.label :id
        = flight_form.text_field :id

    = form.submit

app/views/admin/opportunities/edit.html.slim
h1 Editing Opportunity

= render 'form', opportunity: @opportunity

= link_to 'Show', [:admin, @opportunity]
= link_to 'Back', admin_opportunities_path

app/views/admin/opportunities/index.html.slim
- content_for :sidebar
  = render 'admin/cities/sidebar'

p#notice= notice

= link_to 'New', new_admin_city_opportunity_path

h1 Opportunities
table
  thead
    tr
      th Flight
      th Hotel reservation
      th colspan="3" 
  tbody
    - @opportunities.each do |opportunity|
      tr
        td= opportunity.flight
        td= opportunity.hotel_reservation
        / td= link_to 'Show', admin_city_opportunity_path(params[:city_id])
        / td= link_to 'Edit', edit_opportunity_path(opportunity)
        / td= link_to 'Destroy', opportunity, method: :delete, data: { confirm: 'Are you sure?' }
br
/ = link_to 'New Opportunity', new_opportunity_path

app/views/admin/opportunities/new.html.slim
h1 New Opportunity

= render 'form', opportunity: @opportunity

br

= link_to 'Back', admin_city_opportunities_path

app/views/admin/opportunities/show.html.slim
/ p#notice
/   | <%= notice %>

= @opportunity.image.methods
/ = image_tag @opportunity.image.variant(resize: "500x500")

p
  strong Flight:

= @opportunity.flight

p
  strong Hotel reservation:

= @opportunity.hotel_reservation

= link_to 'Back', admin_opportunities_path