config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :saved_filters do
    get 'activate', on: :collection
    get 'deactivate', on: :collection
  end

  devise_for :users

  root to: 'home#index'

  # resource :weather, only: :index,
  #
  get 'weather_forecasts/get_weather_forecast',
      to: 'weather_forecasts#get_weather_forecast',
      as: :get_weather_forecast

  get 'flights/:id/anywhere',
      to: 'cities#anywhere',
      as: :flights_to_anywhere

  get 'flights/:city_from/:city_to',
      to: 'cities#flights_to_selected_city',
      as: :flights_to_selected_city

  resources :cities, only: %i[index show] do
    get :flights_statistics, on: :member
  end

  # Admin part
  get '/admin', to: 'admin#index', as: :admin_home

  scope :admin, module: :admin, as: :admin do
    root to: 'home#index'

    resources :cities do
      resources :opportunities
      resources :hotel_reservations
      resources :flights

      get 'destinations', on: :member, as: :cheapest
      get 'stats', on: :member, as: :stats
    end

    resources :countries
  end

  # Utilities
  require 'sidekiq/web'
  require "fastentry/engine"
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
    mount Fastentry::Engine, at: '/fastentry'
  end

  mount ActionCable.server => '/cable'

  authenticate :user, ->(user) { user.has_role? :admin } do
    mount PgHero::Engine, at: 'pghero'
  end
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  enum currency: { USD: 0, RUB: 1, EUR: 2, UAH: 3, BYN: 4 }
  attr_accessor :featured

  belongs_to :country,
             foreign_key: 'country_code',
             primary_key: 'code',
             optional: true

  scope :enabled_departure_cities, -> { where(title: Settings.enabled_departure_cities.keys) }
  scope :enabled_ariving_cities, -> { where(title: Settings.europe_arriving_cities.keys) }

  has_many :departing_flights, class_name: 'Flight', foreign_key: :city_from_id
  has_many :arriving_flights, class_name: 'Flight', foreign_key: :city_to_id

  has_many :destinations, class_name: 'Destination', foreign_key: :city_from_id

  has_many :opportunities, through: :departing_flights, foreign_key: 'id'

  has_many :hotel_reservations

  # has_many :images
  has_many_attached :images, dependent: :destroy

  has_many_attached :covers, dependent: :destroy
  # has_one :destination
  #
  def flight_with_min_price
    Flight
      .where(city_to_id: id, currency: :RUB)
      .order(:cost)
      .limit(1)
      &.first
  end
end

app/controllers/admin/cities_controller.rb
# frozen_string_literal: true

class Admin::CitiesController < AdminController
  before_action :set_city, only: %i[show edit update destroy month_flights cheapest_flights popular_directions latest destinations stats]
  skip_before_action :authenticate_user!, :authorize_user!, only: [:show]

  def index
    @cities = City.enabled_departure_cities
  end

  def flights_statistics
    render json: Flight.statistics(@city.id).to_json
  end

  def show
    @flights = @city
               .departing_flights
               .order_scope(params[:order] || nil, params[:direction])
               .order(created_at: :desc)
               .includes(:city_from)
               .includes(:city_to)
               .paginate(page: params[:page], per_page: 100)
               .by_arriving_city(params[:city] || nil)
               .by_source(params[:source] || nil)
               .by_departing_date(params[:departure_date_from] || nil)
               .by_arriving_date(params[:arrive_date_from] || nil)

    @cities = City
              .where(id: Flight.find_by_sql("SELECT DISTINCT city_to_id FROM flights WHERE city_from_id = #{@city.id}")
                .pluck(:city_to_id))
  end

  def new
    @city = City.new
  end

  def edit; end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def month_flights
    @flights = FlightSearchService.month
    # @flights.sort do |flight1, flight2|
    # Date.parse(flight1['depart_date']) < Date.parse(flight2['depart_date'])
    # p flight1.inspect
    # p Date.parse(flight1['depart_date'])
    # p '------------'
    # p flight2.inspect
    # p Date.parse(flight2['depart_date'])
    # end
    @cities = City.where(code: @flights.pluck('destination'))
  end

  def cheapest_flights
    @flights = FlightSearchService.cheapest
    @cities = City.where(code: @flights.keys)
  end

  def popular_directions
    @directions = FlightSearchService.popular_directions
    @cities = City.where(code: @directions.keys)
  end

  def destinations
    @destinations = @city.destinations.includes(:city_to)
  end

  def stats
    @latest = @city
              .departing_flights
              .where(source: :latest)
              .group_by_day(:created_at, range: 3.month.ago.to_date..Date.today, format: '%Y-%m-%d')
              .count

    @direct = @city
              .departing_flights
              .where(source: :direct)
              .group_by_day(:created_at, range: 3.month.ago.to_date..Date.today, format: '%Y-%m-%d')
              .count

    @nearest = @city
               .departing_flights
               .where(source: :nearest)
               .group_by_day(:created_at, range: 3.month.ago.to_date..Date.today, format: '%Y-%m-%d')
               .count

    @cheapest = @city
                .departing_flights
                .where(source: :nearest)
                .group_by_day(:created_at, range: 3.month.ago.to_date..Date.today, format: '%Y-%m-%d')
                .count

    @sourceless = @city
                  .departing_flights
                  .where(source: nil)
                  .group_by_day(:created_at, range: 3.month.ago.to_date..Date.today, format: '%Y-%m-%d')
                  .count
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:title, :slug, :lat, :lng, :country_id, :departure_date_from)
  end
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  before_action :set_city, only: %i[show search flights_statistics flights anywhere]
  before_action :set_cities_by_code, only: %i[flights_to_selected_city]

  def show
    # @opportunities = CityOpportunitiesQuery.new.call(@city.opportunities, params)
    @fligts_count = Flight.where(city_from_id: @city.id).group(:city_to_id).count

    @destinations = Destination
                      .where(city_from_id: @city.id, city_to_id: @fligts_count.keys)
                      .includes(:city_to, :city_from)
                      .order('cities.title')
                      .group_by { |destination| destination.city_to.country_code }

    @countries = Country
                   .where(code: @destinations.keys)
                    .with_attached_flag
                   .order(title: :asc)
    # @minimal_prices = Flight
    #                     .order(:cost)
    #                     .distinct(:city_to_id)
    #                     .where(city_to_id: @fligts_count.keys)

  end

  def flights
    handle_flights_from_cache
  end

  def anywhere
    handle_flights_from_cache
    @url = flights_to_anywhere_path(@city)
    render :flights
  end

  def flights_to_selected_city
    @url = flights_to_selected_city_path(@city.code, @city_to.code)
    handle_flights_from_cache
  end

  def search
    @cities = City
                .where(id: Flight.find_by_sql("SELECT DISTINCT city_to_id FROM flights WHERE city_from_id = #{@city.id}").pluck(:city_to_id))
  end

  private

  def set_city
    @city = City.find(params[:id])
  end

  def set_cities_by_code
    @city = City.find_by_code(params[:city_from].upcase)
    @city_to = City.find_by_code(params[:city_to].upcase)
    @destination = Destination.where(city_from_id: @city.id, city_to_id: @city_to.id).limit(1).first
    @flight_with_min_price = @destination&.flight_with_min_price
  end

  def handle_flights_from_cache
    @flights = Rails.cache.fetch("#{request.url}/flights", expires_in: 10.minutes)
    @flights_cities = Rails.cache.fetch("#{request.url}/flights_cities", expires_in: 10.minutes)
    @cities = Rails.cache.fetch("#{request.url}/cities", expires_in: 10.minutes)

    fetch_flights_from_cache unless @flights && @flights_cities && @cities
  end

  def fetch_flights_from_cache
    @flights = @city
               .departing_flights
               .order_scope(params[:order] || nil, params[:direction])
               .order(created_at: :desc)
               .includes(:city_from)
               .includes(:city_to)
               .paginate(page: params[:page], per_page: 100)
               .by_including_dates(params[:date_in] || nil)
               .by_arriving_city(params[:city] || @city_to&.code || nil)
               .by_source(params[:source] || nil)
               .by_departing_date(params[:date_from] || nil)
               .by_arriving_date(params[:date_to] || nil)
               .by_max_price(params[:max_price] || nil)

    Rails.cache.write("#{request.url}/flights", @flights)

    @flights_cities = @city
                      .departing_flights
                      .includes(:city_from)
                      .includes(:city_to)
                      .by_departing_date(params[:date_from] || nil)
                      .by_arriving_date(params[:date_to] || nil)
                      .by_max_price(params[:max_price] || nil)
                      .distinct('flights.city_to_id')
                      .pluck('flights.city_to_id')

    Rails.cache.write("#{request.url}/flights_cities", @flights_cities)

    @cities = City.where(id: @flights_cities).order(title: :asc)

    Rails.cache.write("#{request.url}/cities", @cities)
  end
end

app/helpers/cities_helper.rb
# frozen_string_literal: true

module CitiesHelper
  def city_name_by_locale(city)
    if locale == :ru
      city.title
    else
      city&.additional_data.dig('name_translations', 'en') || city.title
    end
  end

  def settings
    {
      MOW: {
        currency: :rub,
        locale: :ru
      },
      NYC: {
        currency: :usd,
        locale: :en
      }
    }
  end

  def flight_cities_destinations(flight_cities)
    featured = flight_cities.select { |city| city.featured == true }
    not_featured = flight_cities - featured

    [featured, not_featured]
  end
end

app/views/cities/_cities_info.html.slim
.box data-controller='collapse'
  p В рамках этого фильтра вы можете купить билеты в следующие города (#{ cities.count }):
  button.button data-target="collapse.trigger" Открыть

  - featured, not_featured = flight_cities_destinations(@cities)

  div.is-hidden data-target="collapse.content"
    br

    .columns.is-multiline.is-gapless
      - featured.each do |city|
        .column.is-2-desktop
          .cityToFlight
            .cityToFlight__overlay
            / = image_tag "https://source.unsplash.com/400x200/?#{ city&.additional_data.dig('name_translations', 'en') || city.title }"
            = link_to city.title, url_for(flights_city_path(@city, city: city.code)), class: 'cityToFlight__title'

    p и другие:

    .columns.is-multiline
      - not_featured.each do |city|
        .column.is-2-desktop
          = link_to city.title, url_for(flights_city_path(@city, city: city.code))

app/views/cities/_navigation.html.slim
.tabs.is-centered
  ul
    li class=('is-active' if current_page?(action: 'show'))
      = link_to_if !current_page?(action: 'show'), t('compilation'), city_path(@city)
    li class=('is-active' if current_page?(action: 'flights'))
      = link_to_if !current_page?(action: 'flights'), t('manual_search'), flights_city_path(@city)

app/views/cities/flights.html.slim
br

/ = render 'navigation'

h1.title.is-1 Обновления билетов

div data-controller='latest-flights-filter' data-latest-flights-filter-city-from=@city.id

  = render 'admin/cities/latest_filter_form'

  div data-controller='filters-list'
    div data-target='filters-list.filtersList'

  / = render 'cities/cities_info', cities: @cities


  = render partial: 'flights/list'

app/views/cities/flights_to_selected_city.html.slim
br

/ = render 'navigation'

h1.title.is-1 Авиабилеты #{ @city.title } - #{ @city_to.title } от #{ @flight_with_min_price&.cost } #{ t(@city.currency.downcase, count: @flight_with_min_price&.cost) }

div [
  data-controller='latest-flights-filter'
  data-latest-flights-filter-city-from=@city.id ]

  = render 'admin/cities/latest_filter_form'

  div data-controller='filters-list'
    div data-target='filters-list.filtersList'

  / = render 'cities/cities_info', cities: @cities

  = render partial: 'flights/list'

app/views/cities/search.html.slim
br

div
  = link_to city_path(@city), class: 'button' do
    = svg_icon 'svg_icons-hotel-2', class: 'opportunityBlock__arrow'
    | Return

h1.title.is-1 Обновления билетов

div data-target='filters-list'

div data-controller='latest-flights-filter'

  = render 'admin/cities/latest_filter_form'

  / table.table
  /   thead.thead
  /     tr
  /       th #
  /       th width='200px' = link_to 'В', sort_flights_link(:city_to_id), data: { turbolinks: false }
  /       th = link_to 'Цена', sort_flights_link(:cost), data: { turbolinks: false }
  /       th = link_to 'Вылет', sort_flights_link(:date_from), data: { turbolinks: false }
  /       th = link_to ' Возврат', sort_flights_link(:date_to), data: { turbolinks: false }
  /       / th = link_to ' Длительность', sort_flights_link(:duration)
  /       th Длительность
  /       th = link_to ' Опубликован',sort_flights_link(:created_at), data: { turbolinks: false }
  /       th Пересадки
  /       th Источник
  /       th Ссылка
  /   tbody.tbody
  /     - @flights.each do |flight|
  /       tr.tr
  /         td = flight.city_to.title
  /         td = flight.id
  /         td = flight.cost
  /         td = flight.date_from
  /         td = flight.date_to
  /         td = flight.duration
  /         td = l(flight.created_at, format: '%d %b %H:%M')
  /         td = flight.number_of_changes
  /         td = flight.source
  /         td = link_to 'Aviasales', flight.link, target: :blank
  / / | Из #{ flight.city_from.title } в #{ flight.city_to.title } по #{ flight.cost } вылет #{ flight.date_from } возврат #{ flight.date_to }
  /
  / div data-turbolinks='false'
  /   = will_paginate @flights

app/views/cities/show.html.slim
br

/ = render 'navigation'

/ = render partial: "shared/opportunity",
/   collection: @opportunities
.columns.box
  = link_to 'Куда нибудь',
    flights_to_anywhere_path(@city)

hr

- @countries.each do |country|
  .columns.is-mobile.is-vcentered
    = image_tag country.flag if country.flag.attached?
    .column
      h2.title.is-2 = country.title

  .columns.is-multiline
    = render partial: 'shared/destination',
      collection: @destinations[country.code],
      as: :destination,
      cached: true